CREATE TABLE IF NOT EXISTS `vehicle_assets` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,  
  `asset_id` INT(10) UNSIGNED NOT NULL ,
  `vehicle_type` VARCHAR(100) NOT NULL,
  `certificate_type_id` INT(10) NOT NULL ,
  `certificate_number` VARCHAR(100) NOT NULL ,
  `series` VARCHAR(100) NOT NULL ,
  `brand_id` INT(10) NOT NULL ,
  `type` VARCHAR(100) NOT NULL ,
  `production_year` VARCHAR(100) NOT NULL ,
  `transmission_id` INT(10) NOT NULL ,
  `machine_capacity_id` INT(10) NOT NULL ,
  `color_id` INT(10) NOT NULL ,
  `number_of_seat` VARCHAR(100) NOT NULL ,
  `number_of_usage` VARCHAR(100) NOT NULL ,
  `machine_number` VARCHAR(100) NOT NULL ,
  `body_number` VARCHAR(100) NOT NULL ,
  `licence_date` DATETIME NOT NULL,
  `created_at` DATETIME NULL,
  `updated_at` DATETIME NULL,
  PRIMARY KEY (`id`)
)ENGINE = InnoDB DEFAULT CHARSET=utf8mb4;
