CREATE TABLE IF NOT EXISTS `sub_categories` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,  
  `category_id` INT(10) UNSIGNED NOT NULL ,
  `name` VARCHAR(100) NOT NULL,
  `created_at` DATETIME NULL,
  `updated_at` DATETIME NULL,
  PRIMARY KEY (`id`)  
)ENGINE = InnoDB DEFAULT CHARSET=utf8mb4;
